version: '3'
services:
  # Development container
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    environment: [NODE_ENV=development]
    depends_on: [db]
    volumes: ["../..:/workspaces"]

  # MariaDB Database
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stemchatbot
      MYSQL_USER: bhcc
      MYSQL_PASSWORD: bhcc
    ports: ["5432:5432"]
    volumes: [stemchatbot-mariadb-data:/var/lib/mysql]

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=bhcc
      - PMA_PASSWORD=bhcc

volumes:
  stemchatbot-mariadb-data:
